package com.travelsouvenirs.main.platform

// Warm vintage sepia dark map — matches the Polaroid app theme
internal const val GOOGLE_MAPS_DARK_STYLE_POLAROID = """[{"elementType":"geometry","stylers":[{"color":"#1A140A"}]},{"elementType":"labels.text.fill","stylers":[{"color":"#C8A860"}]},{"elementType":"labels.text.stroke","stylers":[{"color":"#1A140A"}]},{"featureType":"administrative.country","elementType":"geometry.stroke","stylers":[{"color":"#4A3818"},{"weight":0.8}]},{"featureType":"administrative.locality","elementType":"labels.text.fill","stylers":[{"color":"#D4A840"}]},{"featureType":"administrative.province","elementType":"geometry.stroke","stylers":[{"color":"#2A1E0E"}]},{"featureType":"poi","elementType":"labels.text.fill","stylers":[{"color":"#8A6830"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#141A08"}]},{"featureType":"poi.park","elementType":"labels.text.fill","stylers":[{"color":"#3A4818"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#2A200E"}]},{"featureType":"road","elementType":"geometry.stroke","stylers":[{"color":"#1A140A"}]},{"featureType":"road","elementType":"labels.text.fill","stylers":[{"color":"#A88840"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#3A2A10"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#221808"}]},{"featureType":"road.highway","elementType":"labels.text.fill","stylers":[{"color":"#E8D4A0"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#1E180A"}]},{"featureType":"transit.station","elementType":"labels.text.fill","stylers":[{"color":"#C8A040"}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#0E0A06"}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"color":"#4A3818"}]},{"featureType":"water","elementType":"labels.text.stroke","stylers":[{"color":"#0E0A06"}]}]"""

// Warm parchment vintage light map — soft sepia tones for the Polaroid app theme
internal const val GOOGLE_MAPS_LIGHT_STYLE_POLAROID = """[{"elementType":"geometry","stylers":[{"color":"#f0e8d8"}]},{"elementType":"labels.text.fill","stylers":[{"color":"#4a3020"}]},{"elementType":"labels.text.stroke","stylers":[{"color":"#f0e8d8"}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#c8a870"}]},{"featureType":"administrative.locality","elementType":"labels.text.fill","stylers":[{"color":"#3d2008"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#e4d8c4"}]},{"featureType":"poi","elementType":"labels.text.fill","stylers":[{"color":"#6b5040"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#d8e4c8"}]},{"featureType":"poi.park","elementType":"labels.text.fill","stylers":[{"color":"#4a6040"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#ede0c8"}]},{"featureType":"road","elementType":"geometry.stroke","stylers":[{"color":"#d8c8a8"}]},{"featureType":"road","elementType":"labels.text.fill","stylers":[{"color":"#5a4030"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#e0c898"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#c8a870"}]},{"featureType":"road.highway","elementType":"labels.text.fill","stylers":[{"color":"#3d2008"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#e8d8c0"}]},{"featureType":"transit.station","elementType":"labels.text.fill","stylers":[{"color":"#7a5030"}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#a8c0d0"}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"color":"#3a5870"}]}]"""

internal fun darkMapStyle(): String = GOOGLE_MAPS_DARK_STYLE_POLAROID
