package com.travelsouvenirs.main.platform

import com.travelsouvenirs.main.theme.AppStyle

// Cosmic: cool dark purple — matches the default app theme
internal const val GOOGLE_MAPS_DARK_STYLE_COSMIC = """[{"elementType":"geometry","stylers":[{"color":"#1E1C25"}]},{"elementType":"labels.text.fill","stylers":[{"color":"#B0AAC0"}]},{"elementType":"labels.text.stroke","stylers":[{"color":"#1E1C25"}]},{"featureType":"administrative.country","elementType":"geometry.stroke","stylers":[{"color":"#5E5680"},{"weight":0.8}]},{"featureType":"administrative.locality","elementType":"labels.text.fill","stylers":[{"color":"#D0BCFF"}]},{"featureType":"administrative.province","elementType":"geometry.stroke","stylers":[{"color":"#3A3650"}]},{"featureType":"poi","elementType":"labels.text.fill","stylers":[{"color":"#8878B0"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#1A1E2E"}]},{"featureType":"poi.park","elementType":"labels.text.fill","stylers":[{"color":"#505870"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#2A2838"}]},{"featureType":"road","elementType":"geometry.stroke","stylers":[{"color":"#1E1C25"}]},{"featureType":"road","elementType":"labels.text.fill","stylers":[{"color":"#9890B0"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#3C3850"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#282540"}]},{"featureType":"road.highway","elementType":"labels.text.fill","stylers":[{"color":"#CFC6E8"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#24222E"}]},{"featureType":"transit.station","elementType":"labels.text.fill","stylers":[{"color":"#A090D0"}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#0D0C18"}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"color":"#484668"}]},{"featureType":"water","elementType":"labels.text.stroke","stylers":[{"color":"#0D0C18"}]}]"""

// Gateway: steel-blue sky with International Orange accents — matches the Gateway app theme
internal const val GOOGLE_MAPS_DARK_STYLE_GATEWAY = """[{"elementType":"geometry","stylers":[{"color":"#0D1F33"}]},{"elementType":"labels.text.fill","stylers":[{"color":"#B8C8D8"}]},{"elementType":"labels.text.stroke","stylers":[{"color":"#0D1F33"}]},{"featureType":"administrative.country","elementType":"geometry.stroke","stylers":[{"color":"#1E3A50"},{"weight":0.8}]},{"featureType":"administrative.locality","elementType":"labels.text.fill","stylers":[{"color":"#D05A28"}]},{"featureType":"administrative.province","elementType":"geometry.stroke","stylers":[{"color":"#162838"}]},{"featureType":"poi","elementType":"labels.text.fill","stylers":[{"color":"#608098"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#0E2218"}]},{"featureType":"poi.park","elementType":"labels.text.fill","stylers":[{"color":"#2A5A30"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#162838"}]},{"featureType":"road","elementType":"geometry.stroke","stylers":[{"color":"#0D1F33"}]},{"featureType":"road","elementType":"labels.text.fill","stylers":[{"color":"#8AABB8"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#1E3248"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#102030"}]},{"featureType":"road.highway","elementType":"labels.text.fill","stylers":[{"color":"#E8A870"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#102030"}]},{"featureType":"transit.station","elementType":"labels.text.fill","stylers":[{"color":"#D05A28"}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#081426"}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"color":"#1E3A50"}]},{"featureType":"water","elementType":"labels.text.stroke","stylers":[{"color":"#081426"}]}]"""

// Ember: warm charcoal with amber/copper tones — matches the Ember app theme
internal const val GOOGLE_MAPS_DARK_STYLE_EMBER = """[{"elementType":"geometry","stylers":[{"color":"#1C1410"}]},{"elementType":"labels.text.fill","stylers":[{"color":"#C8A87A"}]},{"elementType":"labels.text.stroke","stylers":[{"color":"#1C1410"}]},{"featureType":"administrative.country","elementType":"geometry.stroke","stylers":[{"color":"#6B4E30"},{"weight":0.8}]},{"featureType":"administrative.locality","elementType":"labels.text.fill","stylers":[{"color":"#FFB347"}]},{"featureType":"administrative.province","elementType":"geometry.stroke","stylers":[{"color":"#4A3020"}]},{"featureType":"poi","elementType":"labels.text.fill","stylers":[{"color":"#A07850"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#1A1C0E"}]},{"featureType":"poi.park","elementType":"labels.text.fill","stylers":[{"color":"#604830"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#2E2018"}]},{"featureType":"road","elementType":"geometry.stroke","stylers":[{"color":"#1C1410"}]},{"featureType":"road","elementType":"labels.text.fill","stylers":[{"color":"#A08860"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#3E2A18"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#2A1C0C"}]},{"featureType":"road.highway","elementType":"labels.text.fill","stylers":[{"color":"#E8C878"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#221810"}]},{"featureType":"transit.station","elementType":"labels.text.fill","stylers":[{"color":"#C08040"}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#0E0A06"}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"color":"#5C4830"}]},{"featureType":"water","elementType":"labels.text.stroke","stylers":[{"color":"#0E0A06"}]}]"""

internal fun darkMapStyle(appStyle: AppStyle): String = when (appStyle) {
    AppStyle.COSMIC   -> GOOGLE_MAPS_DARK_STYLE_COSMIC
    AppStyle.GATEWAY  -> GOOGLE_MAPS_DARK_STYLE_GATEWAY
    AppStyle.EMBER    -> GOOGLE_MAPS_DARK_STYLE_EMBER
}
