package com.travelsouvenirs.main.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val CosmicColorScheme: ColorScheme = darkColorScheme()

val GatewayColorScheme: ColorScheme = darkColorScheme(
    primary                = Color(0xFFD05A28),
    onPrimary              = Color(0xFF3A0C00),
    primaryContainer       = Color(0xFF7A2A0A),
    onPrimaryContainer     = Color(0xFFFFDCC8),
    secondary              = Color(0xFFE8A870),
    onSecondary            = Color(0xFF3A1800),
    secondaryContainer     = Color(0xFF5A2A0E),
    onSecondaryContainer   = Color(0xFFFFDCC0),
    tertiary               = Color(0xFF7DAA88),
    onTertiary             = Color(0xFF1A3A1A),
    tertiaryContainer      = Color(0xFF2A5A30),
    onTertiaryContainer    = Color(0xFFB8DCBA),
    error                  = Color(0xFFFFB4AB),
    onError                = Color(0xFF690005),
    errorContainer         = Color(0xFF93000A),
    onErrorContainer       = Color(0xFFFFDAD6),
    background             = Color(0xFF0D1F33),
    onBackground           = Color(0xFFE0D0C8),
    surface                = Color(0xFF0D1F33),
    onSurface              = Color(0xFFE0D0C8),
    surfaceVariant         = Color(0xFF1E3A50),
    onSurfaceVariant       = Color(0xFFB8C8D8),
    outline                = Color(0xFF608098),
    outlineVariant         = Color(0xFF1E3A50),
    surfaceContainerLowest  = Color(0xFF081426),
    surfaceContainerLow     = Color(0xFF102030),
    surfaceContainer        = Color(0xFF162838),
    surfaceContainerHigh    = Color(0xFF1E3248),
    surfaceContainerHighest = Color(0xFF263C52),
    inverseSurface         = Color(0xFFE0D0C8),
    inverseOnSurface       = Color(0xFF1A2C3A),
    inversePrimary         = Color(0xFF8A3010),
    scrim                  = Color(0xFF000000),
)

val EmberColorScheme: ColorScheme = darkColorScheme(
    primary                = Color(0xFFFFB347),
    onPrimary              = Color(0xFF3D1E00),
    primaryContainer       = Color(0xFF6B3600),
    onPrimaryContainer     = Color(0xFFFFDCB5),
    secondary              = Color(0xFFFFCC80),
    onSecondary            = Color(0xFF402000),
    secondaryContainer     = Color(0xFF5C3100),
    onSecondaryContainer   = Color(0xFFFFDCB5),
    tertiary               = Color(0xFFC8A45E),
    onTertiary             = Color(0xFF352000),
    tertiaryContainer      = Color(0xFF4D3000),
    onTertiaryContainer    = Color(0xFFF5DFA0),
    error                  = Color(0xFFFFB4AB),
    onError                = Color(0xFF690005),
    errorContainer         = Color(0xFF93000A),
    onErrorContainer       = Color(0xFFFFDAD6),
    background             = Color(0xFF1C1410),
    onBackground           = Color(0xFFEFE0D0),
    surface                = Color(0xFF1C1410),
    onSurface              = Color(0xFFEFE0D0),
    surfaceVariant         = Color(0xFF4E3C2E),
    onSurfaceVariant       = Color(0xFFD2BFA8),
    outline                = Color(0xFF9C8570),
    outlineVariant         = Color(0xFF4E3C2E),
    surfaceContainerLowest  = Color(0xFF16100C),
    surfaceContainerLow     = Color(0xFF201610),
    surfaceContainer        = Color(0xFF281E16),
    surfaceContainerHigh    = Color(0xFF32261C),
    surfaceContainerHighest = Color(0xFF3C2E22),
    inverseSurface         = Color(0xFFEFE0D0),
    inverseOnSurface       = Color(0xFF352818),
    inversePrimary         = Color(0xFF884E00),
    scrim                  = Color(0xFF000000),
)

val PolaroidColorScheme: ColorScheme = lightColorScheme(
    primary                = Color(0xFF3D2008),
    onPrimary              = Color(0xFFFFFFFF),
    primaryContainer       = Color(0xFF7A4520),
    onPrimaryContainer     = Color(0xFFFFECDE),
    secondary              = Color(0xFF6B5040),
    onSecondary            = Color(0xFFFFFFFF),
    secondaryContainer     = Color(0xFFEDD5C0),
    onSecondaryContainer   = Color(0xFF2A1508),
    tertiary               = Color(0xFF4A6040),
    onTertiary             = Color(0xFFFFFFFF),
    tertiaryContainer      = Color(0xFFCCDFBE),
    onTertiaryContainer    = Color(0xFF0E2010),
    error                  = Color(0xFFBA1A1A),
    onError                = Color(0xFFFFFFFF),
    errorContainer         = Color(0xFFFFDAD6),
    onErrorContainer       = Color(0xFF410002),
    background             = Color(0xFFEDE4D4),
    onBackground           = Color(0xFF1C1208),
    surface                = Color(0xFFFFFBF5),
    onSurface              = Color(0xFF1C1208),
    surfaceVariant         = Color(0xFFE8D8C8),
    onSurfaceVariant       = Color(0xFF4A3A2A),
    outline                = Color(0xFF8A7060),
    outlineVariant         = Color(0xFFD8C8B8),
    surfaceContainerLowest  = Color(0xFFFFFBF5),
    surfaceContainerLow     = Color(0xFFF8F0E4),
    surfaceContainer        = Color(0xFFF2E8D8),
    surfaceContainerHigh    = Color(0xFFECE0CC),
    surfaceContainerHighest = Color(0xFFE6D8C2),
    inverseSurface         = Color(0xFF2C1A08),
    inverseOnSurface       = Color(0xFFEDE4D4),
    inversePrimary         = Color(0xFFFFB870),
    scrim                  = Color(0xFF000000),
)
